<?php

return [

    'destin' => [
        'slug' => 'destin',
        'name' => 'Destin',
        'display_name' => 'Destin, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From the Destin Harbor to Crab Island — websites that bring local customers to your door.',
        'meta_description' => 'Web design and SEO for Destin, FL businesses — charter captains, beachfront restaurants, vacation rentals, and local services. Plans from $299/month.',
        'intro' => "Destin's economy runs on local services and a steady stream of visitors looking for charters, restaurants, and rentals. We build sites that rank for the searches your future customers are actually making in the Destin area — and we run the SEO that keeps you there.",
        'why_local' => "We live and work on Florida's Gulf Coast. We know what 'shoulder season' means for a Destin charter operator's cash flow, and we know the difference between a tourist searching from out of state and a local searching from East Pass. Your site is built for both.",
        'segments' => [
            ['Charter &amp; fishing operators', 'Get found by anglers searching for half-day charters, deep-sea trips, and family-friendly boats well before they land in Destin.'],
            ['Beach restaurants &amp; bars', 'Beat the chains in local search results with a fast site that converts hungry visitors into reservations.'],
            ['Vacation rentals &amp; real estate', 'Show off your properties with a beautiful site optimized for "Destin vacation rentals" and similar local terms.'],
            ['Local service businesses', 'Plumbers, electricians, contractors, med spas, and dentists — we help year-round businesses win year-round customers.'],
        ],
        'nearby' => [
            ['30A', '30a'],
            ['Panama City Beach', 'panama-city-beach'],
            ['Miramar Beach', 'miramar-beach'],
            ['Sandestin', 'sandestin'],
            ['Fort Walton Beach', 'fort-walton-beach'],
        ],
        'geo' => ['lat' => 30.3935, 'lng' => -86.4958],
    ],

    'panama-city-beach' => [
        'slug' => 'panama-city-beach',
        'name' => 'Panama City Beach',
        'display_name' => 'Panama City Beach, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Pier Park to Front Beach Road — websites that work as hard as PCB does.',
        'meta_description' => 'Web design and SEO for Panama City Beach businesses — vacation rentals, restaurants, charter operators, med spas, and local services. Plans from $299/month.',
        'intro' => 'Panama City Beach is one of the busiest tourist markets on the Gulf, and the local search competition is fierce. We build websites and run SEO programs that help PCB businesses win year-round — not just during spring break.',
        'why_local' => "We're based in Panama City Beach. We know the difference between a Front Beach Road condo manager and a Thomas Drive seafood spot, and your site is built around the customer you actually serve.",
        'segments' => [
            ['Vacation rental managers', 'Custom property sites and listing pages that rank for "PCB vacation rentals" and the specific neighborhoods you manage.'],
            ['Restaurants &amp; family attractions', 'Mobile-fast menus, reservations, and Google profile optimization so visitors find you the moment they arrive.'],
            ['Charter, dive &amp; tour operators', 'Booking-friendly sites that capture customers researching trips weeks before their vacation.'],
            ['Med spas &amp; local services', 'Year-round local SEO that brings in PCB and Lynn Haven residents, not just tourists.'],
        ],
        'nearby' => [
            ['30A', '30a'],
            ['Destin', 'destin'],
            ['Panama City', 'panama-city'],
            ['Lynn Haven', 'lynn-haven'],
            ['Mexico Beach', 'mexico-beach'],
        ],
        'geo' => ['lat' => 30.1766, 'lng' => -85.8055],
    ],

    '30a' => [
        'slug' => '30a',
        'name' => '30A',
        'display_name' => '30A, Florida',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Grayton to Rosemary Beach — websites built for the 30A way.',
        'meta_description' => 'Web design and SEO for 30A businesses — boutiques, vacation rentals, restaurants, and service pros from Seaside to Alys Beach. Plans from $299/month.',
        'intro' => '30A businesses live by their brand. Seaside, WaterColor, Alys, Rosemary — each town has a distinct look and a customer with high expectations. We build sites that hold up next to your storefront, then run the SEO that brings the right people through the door.',
        'why_local' => 'We work with 30A businesses all the way from Dune Allen to Inlet Beach. We understand the difference between a Watercolor real estate office and a Seacrest boutique — your site is designed to look at home in your specific town.',
        'segments' => [
            ['Boutiques &amp; galleries', 'Beautiful, on-brand websites that match the design standard of your storefront and rank for "30A shopping" and town-specific searches.'],
            ['Vacation rental managers', 'Property sites with the polish 30A guests expect, optimized for the towns and neighborhoods you actually manage.'],
            ['Restaurants &amp; cafés', 'Menus, reservations, and content that win the locals-and-visitors mix that 30A restaurants depend on.'],
            ['Real estate &amp; design pros', 'Agent and studio sites built to compete in one of Florida\'s most competitive markets.'],
        ],
        'nearby' => [
            ['Destin', 'destin'],
            ['Panama City Beach', 'panama-city-beach'],
            ['Seaside', 'seaside'],
            ['WaterColor', 'watercolor'],
            ['Rosemary Beach', 'rosemary-beach'],
            ['Alys Beach', 'alys-beach'],
        ],
        'geo' => ['lat' => 30.3299, 'lng' => -86.1559],
    ],

    'miramar-beach' => [
        'slug' => 'miramar-beach',
        'name' => 'Miramar Beach',
        'display_name' => 'Miramar Beach, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Scenic 98 to Silver Sands — websites that turn vacation traffic into year-round customers.',
        'meta_description' => 'Web design and SEO for Miramar Beach, FL businesses — resort shops, restaurants, vacation rentals, and local services along Scenic 98. Plans from $299/month.',
        'intro' => 'Miramar Beach sits in the sweet spot between Destin and Sandestin, with a steady flow of resort guests, second-home owners, and locals running real businesses. We build sites that capture the searches happening from Scenic 98 condos and the outlets at Silver Sands — and run the SEO that keeps you ranking after the season ends.',
        'why_local' => "We know Miramar Beach isn't just \"east of Destin\" — it has its own crowd, its own price points, and its own search patterns. Whether you're on Scenic Gulf Drive or tucked off 98, your site is built around the customers actually looking for you.",
        'segments' => [
            ['Resort shops &amp; boutiques', 'Storefront-quality websites that hold up next to Silver Sands and pull in shoppers searching before they arrive.'],
            ['Restaurants &amp; beach bars', 'Mobile-fast menus and Google profiles tuned for guests deciding where to eat from a Miramar Beach balcony.'],
            ['Vacation rental managers', 'Property pages that rank for "Miramar Beach vacation rentals" and the specific complexes you manage along Scenic Gulf Drive.'],
            ['Local service businesses', 'HVAC, cleaning, contractors, and med spas — year-round SEO that brings in residents, not just tourists.'],
        ],
        'nearby' => [
            ['Destin', 'destin'],
            ['Sandestin', 'sandestin'],
            ['30A', '30a'],
            ['Fort Walton Beach', 'fort-walton-beach'],
            ['Panama City Beach', 'panama-city-beach'],
        ],
        'geo' => ['lat' => 30.3838, 'lng' => -86.3618],
    ],

    'sandestin' => [
        'slug' => 'sandestin',
        'name' => 'Sandestin',
        'display_name' => 'Sandestin, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Baytowne Wharf to the Burnt Pine fairways — websites built for the Sandestin standard.',
        'meta_description' => 'Web design and SEO for Sandestin businesses — resort shops, dining, golf, marina services, and vacation rentals inside the gates and along 98. Plans from $299/month.',
        'intro' => "Sandestin guests expect polish. Whether they're booking a tee time at Burnt Pine, a dinner at Baytowne Wharf, or a week at a bayfront rental, they're researching from their phone the second they decide to come down. We build sites that match the resort's design standard and run the SEO that wins those searches.",
        'why_local' => "We've spent enough time inside the gates to know how different a Baytowne shop is from a Linkside condo manager or a marina charter operator. Your site is built for your specific corner of the resort — not a generic \"Destin-area\" template.",
        'segments' => [
            ['Resort shops &amp; dining', 'On-brand sites and search visibility for businesses at Baytowne Wharf and around the resort.'],
            ['Vacation rentals &amp; condo managers', 'Listings and search optimization for Sandestin\'s bayside, beachside, and golf-course properties.'],
            ['Golf, tennis &amp; marina services', 'Booking-friendly sites that capture guests planning Sandestin trips weeks in advance.'],
            ['Wedding &amp; event vendors', 'Photographer, florist, and planner sites tuned for couples searching "Sandestin weddings".'],
        ],
        'nearby' => [
            ['Miramar Beach', 'miramar-beach'],
            ['Destin', 'destin'],
            ['30A', '30a'],
            ['Fort Walton Beach', 'fort-walton-beach'],
            ['Panama City Beach', 'panama-city-beach'],
        ],
        'geo' => ['lat' => 30.3838, 'lng' => -86.3293],
    ],

    'fort-walton-beach' => [
        'slug' => 'fort-walton-beach',
        'name' => 'Fort Walton Beach',
        'display_name' => 'Fort Walton Beach, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Okaloosa Island to the Eglin gate — websites built for FWB\'s year-round economy.',
        'meta_description' => 'Web design and SEO for Fort Walton Beach businesses — local services, restaurants, military-friendly shops, and Okaloosa Island rentals. Plans from $299/month.',
        'intro' => "Fort Walton Beach runs differently than Destin. There's a real year-round base of military families, retirees, and locals — plus a strong tourist pull on Okaloosa Island. We build sites and SEO programs that win the everyday searches, not just the spring-and-summer rush.",
        'why_local' => 'We understand the FWB customer mix — Eglin and Hurlburt households, longtime residents on Beal Parkway, and visitors crossing the bridge to the island. Your site is built to bring in the customer base you actually serve.',
        'segments' => [
            ['Local service businesses', 'Plumbers, HVAC, auto repair, contractors — pages that rank for FWB neighborhood searches all year.'],
            ['Restaurants &amp; family attractions', 'Mobile-fast menus and Google profiles that win both locals and Okaloosa Island visitors.'],
            ['Military-friendly retailers &amp; services', 'Sites that speak to Eglin and Hurlburt families, with content that ranks for "near Eglin" searches.'],
            ['Okaloosa Island rentals &amp; charters', 'Booking-ready property and trip sites optimized for the island\'s specific search terms.'],
        ],
        'nearby' => [
            ['Destin', 'destin'],
            ['Miramar Beach', 'miramar-beach'],
            ['Sandestin', 'sandestin'],
            ['Navarre', null],
            ['30A', '30a'],
        ],
        'geo' => ['lat' => 30.4058, 'lng' => -86.6187],
    ],

    'panama-city' => [
        'slug' => 'panama-city',
        'name' => 'Panama City',
        'display_name' => 'Panama City, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Historic St. Andrews to Harrison Avenue — websites built for the real, year-round Panama City.',
        'meta_description' => 'Web design and SEO for Panama City, FL businesses — downtown shops, St. Andrews restaurants, contractors, medical practices, and local services. Plans from $299/month.',
        'intro' => "Panama City is where the year-round economy lives. Downtown's coming back, St. Andrews is full of local favorites, and the surrounding neighborhoods are packed with the trades, medical practices, and service businesses that keep the area running. We build sites and SEO programs designed for that everyday customer, not just the beach crowd.",
        'why_local' => 'We know the difference between a Harrison Avenue retailer, a Cove dentist, and a contractor working out of Lynn Haven. Your site is built for the customers in your actual service area — not lumped in with Panama City Beach.',
        'segments' => [
            ['Trades &amp; home services', 'Roofers, electricians, plumbers, and remodelers — local SEO that wins neighborhood-level searches across Bay County.'],
            ['Medical, dental &amp; professional', 'Practice sites and content that rank for Panama City service searches, not generic state-wide terms.'],
            ['Downtown &amp; St. Andrews shops', 'On-brand sites for the small businesses driving Panama City\'s comeback.'],
            ['Restaurants &amp; cafés', 'Mobile-fast menus and Google profile work that brings in locals night after night.'],
        ],
        'nearby' => [
            ['Panama City Beach', 'panama-city-beach'],
            ['Lynn Haven', 'lynn-haven'],
            ['Mexico Beach', 'mexico-beach'],
            ['30A', '30a'],
            ['Callaway', null],
        ],
        'geo' => ['lat' => 30.1588, 'lng' => -85.6602],
    ],

    'lynn-haven' => [
        'slug' => 'lynn-haven',
        'name' => 'Lynn Haven',
        'display_name' => 'Lynn Haven, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Sheffield Park to Highway 77 — websites built for Lynn Haven\'s growing year-round community.',
        'meta_description' => 'Web design and SEO for Lynn Haven, FL businesses — contractors, medical practices, family-owned shops, and local services. Plans from $299/month.',
        'intro' => 'Lynn Haven keeps growing — new families, new builds, and a steady demand for local services. We build websites and run SEO that puts your business in front of the homeowners actually moving in and searching for you on Google.',
        'why_local' => "We work with businesses across Bay County and we know Lynn Haven's customer is different from Panama City Beach's. Your site is tuned for the year-round residents, families, and local pros who shop here every day.",
        'segments' => [
            ['Trades &amp; home services', 'Contractors, lawn care, HVAC, and remodelers — content that ranks for "Lynn Haven" plus the services you actually offer.'],
            ['Medical &amp; dental practices', 'Patient-friendly sites tuned for the families and retirees who choose providers close to home.'],
            ['Family-owned shops &amp; restaurants', 'On-brand sites and Google profile work that win local search across Lynn Haven.'],
            ['Professional services', 'Attorneys, accountants, and insurance offices — local SEO that brings in Lynn Haven and north Bay County clients.'],
        ],
        'nearby' => [
            ['Panama City', 'panama-city'],
            ['Panama City Beach', 'panama-city-beach'],
            ['Mexico Beach', 'mexico-beach'],
            ['30A', '30a'],
            ['Southport', null],
        ],
        'geo' => ['lat' => 30.2466, 'lng' => -85.6479],
    ],

    'mexico-beach' => [
        'slug' => 'mexico-beach',
        'name' => 'Mexico Beach',
        'display_name' => 'Mexico Beach, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From the canal to Highway 98 — websites built for Mexico Beach\'s small-town comeback.',
        'meta_description' => 'Web design and SEO for Mexico Beach, FL businesses — vacation rentals, restaurants, charter captains, and small-town service pros. Plans from $299/month.',
        'intro' => 'Mexico Beach is rebuilding into something special — quieter than PCB, with a loyal returning crowd and a tight-knit business community. We build sites and run SEO that puts you in front of the visitors planning their trip and the locals choosing where to spend.',
        'why_local' => "We know Mexico Beach isn't trying to be Panama City Beach, and we won't market it that way. Your site reflects the slower, smaller, repeat-visitor town your customers are actually coming to find.",
        'segments' => [
            ['Vacation rental managers &amp; owners', 'Property sites that capture the families who book Mexico Beach year after year.'],
            ['Restaurants &amp; small shops', 'Sites and Google profiles that win the visitor researching dinner from a canal-side rental.'],
            ['Charter captains &amp; outdoor outfitters', 'Booking-friendly trip sites optimized for anglers searching well before they arrive.'],
            ['Local service businesses', 'Contractors, cleaners, and trades — year-round SEO for the residents and second-home owners rebuilding the community.'],
        ],
        'nearby' => [
            ['Panama City Beach', 'panama-city-beach'],
            ['Panama City', 'panama-city'],
            ['Lynn Haven', 'lynn-haven'],
            ['Port St. Joe', null],
            ['30A', '30a'],
        ],
        'geo' => ['lat' => 29.9469, 'lng' => -85.4116],
    ],

    'seaside' => [
        'slug' => 'seaside',
        'name' => 'Seaside',
        'display_name' => 'Seaside, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From the Amphitheater to Central Square — websites that match the Seaside standard.',
        'meta_description' => 'Web design and SEO for Seaside, FL businesses — boutiques, restaurants, galleries, and vacation rentals at the original 30A town. Plans from $299/month.',
        'intro' => 'Seaside set the design standard the rest of 30A is still chasing. Your customers — boutique shoppers, second-home owners, design-conscious families — expect a website that lives up to the storefront. We build sites that do, and run the SEO that brings the right kind of traffic to your door.',
        'why_local' => 'Working with Seaside businesses means respecting the brand of the town itself. Pastel-perfect, walkable, hand-built — your site should feel like an extension of Central Square, not a generic real-estate-template knockoff.',
        'segments' => [
            ['Boutiques, galleries &amp; design shops', 'On-brand sites that match the Seaside aesthetic and rank for shopping searches up and down 30A.'],
            ['Restaurants &amp; cafés', 'Menus, reservations, and Google profile work tuned for the locals-and-visitors mix Seaside spots depend on.'],
            ['Vacation rentals &amp; cottage managers', 'Property pages with the polish Seaside guests expect, plus SEO for the specific cottages you manage.'],
            ['Real estate &amp; design pros', 'Agent and studio sites built to compete in one of Florida\'s most premium markets.'],
        ],
        'nearby' => [
            ['WaterColor', 'watercolor'],
            ['30A', '30a'],
            ['Rosemary Beach', 'rosemary-beach'],
            ['Alys Beach', 'alys-beach'],
            ['Destin', 'destin'],
        ],
        'geo' => ['lat' => 30.3211, 'lng' => -86.1481],
    ],

    'watercolor' => [
        'slug' => 'watercolor',
        'name' => 'WaterColor',
        'display_name' => 'WaterColor, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Western Lake to the BeachClub — websites built for the WaterColor brand.',
        'meta_description' => 'Web design and SEO for WaterColor, FL businesses — vacation rentals, restaurants, boutiques, and design pros at one of 30A\'s premier communities. Plans from $299/month.',
        'intro' => "WaterColor guests come for the dune lake, the BeachClub, and the kind of design-led vacation you can't fake. We build sites and SEO programs for the businesses serving that customer — without the generic \"30A vacation rental\" template the search results are full of.",
        'why_local' => 'We know the WaterColor customer is different from a Seacrest renter or a Destin condo guest. Your site is built around the price point, the polish, and the searches that actually convert here.',
        'segments' => [
            ['Vacation rental managers', 'Property sites and listing pages optimized for WaterColor cottages, homes, and BeachClub-access rentals.'],
            ['Boutiques &amp; lifestyle shops', 'On-brand websites that match the WaterColor design standard and pull in shoppers from across 30A.'],
            ['Restaurants &amp; cafés', 'Menus and Google profiles tuned for the guests deciding where to eat from a Western Lake porch.'],
            ['Real estate &amp; design pros', 'Agent and studio sites built for one of 30A\'s most competitive markets.'],
        ],
        'nearby' => [
            ['Seaside', 'seaside'],
            ['30A', '30a'],
            ['Rosemary Beach', 'rosemary-beach'],
            ['Alys Beach', 'alys-beach'],
            ['Destin', 'destin'],
        ],
        'geo' => ['lat' => 30.3303, 'lng' => -86.1361],
    ],

    'rosemary-beach' => [
        'slug' => 'rosemary-beach',
        'name' => 'Rosemary Beach',
        'display_name' => 'Rosemary Beach, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From Town Hall to the boardwalks — websites built for Rosemary\'s distinctive standard.',
        'meta_description' => 'Web design and SEO for Rosemary Beach, FL businesses — vacation rentals, boutiques, restaurants, and design pros at one of 30A\'s most distinctive towns. Plans from $299/month.',
        'intro' => 'Rosemary Beach has a look you can spot from a block away — Dutch West Indies architecture, narrow walkways, deep porches, and a customer who notices the difference. We build websites that hold up to that level of detail, and run the SEO that brings the right guests through your door.',
        'why_local' => "We've worked with enough 30A businesses to know Rosemary's not just another beach town. Your site is built around the design sensibility, price point, and customer Rosemary actually attracts.",
        'segments' => [
            ['Boutiques &amp; galleries', 'On-brand sites that match Rosemary\'s storefront standard and rank for east-end-of-30A shopping searches.'],
            ['Restaurants &amp; wine bars', 'Menus, reservations, and Google profile work for the locals-and-visitors mix Rosemary spots count on.'],
            ['Vacation rental managers', 'Property sites with the polish Rosemary guests expect, optimized for the specific homes you manage.'],
            ['Real estate &amp; design pros', 'Agent and studio sites built to compete in one of 30A\'s most premium pockets.'],
        ],
        'nearby' => [
            ['Alys Beach', 'alys-beach'],
            ['Seaside', 'seaside'],
            ['WaterColor', 'watercolor'],
            ['30A', '30a'],
            ['Panama City Beach', 'panama-city-beach'],
        ],
        'geo' => ['lat' => 30.2773, 'lng' => -85.9444],
    ],

    'alys-beach' => [
        'slug' => 'alys-beach',
        'name' => 'Alys Beach',
        'display_name' => 'Alys Beach, FL',
        'tagline' => 'Web Design &amp; SEO',
        'hero_subhead' => 'From the white walls to the Caliza pool — websites built for the Alys standard.',
        'meta_description' => 'Web design and SEO for Alys Beach, FL businesses — vacation rentals, restaurants, design pros, and boutiques at 30A\'s most architectural town. Plans from $299/month.',
        'intro' => 'Alys Beach is unlike anything else on 30A — all-white architecture, courtyards, and a level of design discipline you only get when an entire town is built to one standard. We build websites and run SEO for businesses that have to live up to that, without looking like every other beach-town site on the search results page.',
        'why_local' => 'We respect the Alys brand. Your site should look like it belongs across the courtyard from Caliza — restrained, considered, and built for guests who notice every detail.',
        'segments' => [
            ['Vacation rentals &amp; private homes', 'Property pages with the restraint and polish Alys guests expect.'],
            ['Restaurants &amp; private dining', 'Menus, reservations, and Google profile work for Alys spots competing on experience, not volume.'],
            ['Boutiques &amp; design retail', 'On-brand sites that hold up next to the architecture and rank for the searches your guests are actually running.'],
            ['Architects, designers &amp; real estate', 'Studio and agent sites built to compete in one of the country\'s most design-aware markets.'],
        ],
        'nearby' => [
            ['Rosemary Beach', 'rosemary-beach'],
            ['Seaside', 'seaside'],
            ['WaterColor', 'watercolor'],
            ['30A', '30a'],
            ['Panama City Beach', 'panama-city-beach'],
        ],
        'geo' => ['lat' => 30.2746, 'lng' => -85.9805],
    ],

];
